name: espresso
description: Espresso Application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  talker_dio_logger: ^4.3.4
  flutter_hooks: ^0.20.5
  fquery: ^1.4.0-beta.1
  flutter_native_splash: ^2.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.2
  infinite_scroll_pagination: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  fancy_shimmer_image: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  commitlint_cli: ^0.7.1
  husky: ^0.1.7
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo/PNG/main-logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
